### ISSUE TITLE
Assert Exception:v.size() == 2: method specification invalid. Should be api.method

### ISSUE THREAD

**Issue by iguoke** [SophiaTX/SophiaTX#155]
I follow "Guide to start sync node"(https://github.com/SophiaTX/SophiaTX/wiki/Guide-to-start-sync-node)
then using postman put request({"jsonrpc": "2.0", "method": "info", "params": [], "id": 1540374478060519000})
but return error:

{
    "jsonrpc": "2.0",
    "error": {
        "code": -32002,
        "message": "Assert Exception:v.size() == 2: method specification invalid. Should be api.method",
        "data": {
            "code": 10,
            "name": "assert_exception",
            "message": "Assert Exception",
            "stack": [
                {
                    "context": {
                        "level": "error",
                        "file": "json_rpc_plugin.cpp",
                        "line": 235,
                        "method": "process_params",
                        "hostname": "",
                        "timestamp": "2018-10-26T03:05:49"
                    },
                    "format": "v.size() == 2: method specification invalid. Should be api.method",
                    "data": {}
                }
            ]
        }
    },
    "id": "1540374478060519000"
}
 and The "cli_wallet" common line is passed!
please tell how to do?
thinks

**Comment by MatusKysel** [comment]
You should call **info** instead of **get_info**

**Comment by iguoke** [comment]
> You should call **info** instead of **get_info**

Both "info" or "get_info" are wrong!

**Comment by ejossev** [comment]
Towards which endpoint are you connecting?

**Comment by ejossev** [comment]
Ok, so not against cli_wallet. Then this shall work: 

```
> {"id":1, "jsonrpc":"2.0",  "method":"database_api.get_dynamic_global_properties", "params": {"name":""} }
< {"jsonrpc":"2.0","result":{"id":0,"head_block_number":2664843,"head_block_id":"0028a98b485c07e2b5d4260e9cfc15a9fe5f048f","time":"2018-10-26T11:27:51","current_witness":"phinx","current_supply":"351354415.877634 SPHTX","total_vesting_shares":"13964200.454954 VESTS","total_reward_fund":"0.000000 SPHTX","maximum_block_size":50331648,"current_aslot":2678957,"witness_required_vesting":"250000.000000 VESTS","recent_slots_filled":"340282366920938463463374607431768211455","participation_count":128,"last_irreversible_block_num":2664806},"id":1}
```

**Comment by iguoke** [comment]
"{"id":1, "jsonrpc":"2.0",  "method":"database_api.get_dynamic_global_properties", "params": {"name":""} }" was passed,
And Is there a documentation here?I just find this link:https://github.com/SophiaTX/SophiaTX/wiki/cli_wallet---RPC-calls-documentation
I want to use methods including  create_account/get_block/get_transaction/transfer.. etc

Thank you very much!

**Comment by iguoke** [comment]
> Ok, so not against cli_wallet. Then this shall work:
> 
> ```
> > {"id":1, "jsonrpc":"2.0",  "method":"database_api.get_dynamic_global_properties", "params": {"name":""} }
> < {"jsonrpc":"2.0","result":{"id":0,"head_block_number":2664843,"head_block_id":"0028a98b485c07e2b5d4260e9cfc15a9fe5f048f","time":"2018-10-26T11:27:51","current_witness":"phinx","current_supply":"351354415.877634 SPHTX","total_vesting_shares":"13964200.454954 VESTS","total_reward_fund":"0.000000 SPHTX","maximum_block_size":50331648,"current_aslot":2678957,"witness_required_vesting":"250000.000000 VESTS","recent_slots_filled":"340282366920938463463374607431768211455","participation_count":128,"last_irreversible_block_num":2664806},"id":1}
> ```

"{"id":1, "jsonrpc":"2.0", "method":"database_api.get_dynamic_global_properties", "params": {"name":""} }",that  was passed,
And Is there a documentation here?I just find this link:https://github.com/SophiaTX/SophiaTX/wiki/cli_wallet---RPC-calls-documentation
I want to use methods including create_account/get_block/get_transaction/transfer.. etc

Thank you very much!

**Comment by ejossev** [comment]
That page refers only to cli_wallet. For the main daemon, refer to this: https://developers.sophiatx.com/apidefinitions/#apidefinitions-database-api

**Comment by iguoke** [comment]
> That page refers only to cli_wallet. For the main daemon, refer to this: https://developers.sophiatx.com/apidefinitions/#apidefinitions-database-api

Thinks, But when I posting {"jsonrpc": "2.0", "method": "info", "params": [], "id": 1}  on http://devnet.sophiatx.com:9195, it passed!
{
    "id": 1,
    "result": {
        "head_block_number": 1108775,
        "head_block_id": "0010eb27b105431916a9e5350439cfbdd25dd1bb",
        "time": "2018-10-26T11:53:36",
        "current_witness": "initminer",
        "current_supply": "350549571.619714 SPHTX",
        "total_vesting_shares": "1409210.600365 VESTS",
        "witness_required_vesting": "250000.000000 VESTS",
        "maximum_block_size": 50331648,
        "current_aslot": 2909872,
        "recent_slots_filled": "340282366920938463463374607431768211455",
        "participation_count": 128,
        "last_irreversible_block_num": 1108773,
        "average_block_size": 117,
        "witness_majority_version": "0.0.0",
        "hardfork_version": "1.0.0",
        "head_block_age": "0 second old",
        "participation": "100.00000000000000000",
        "median_sbd1_price": {
            "base": "1.000000 SPHTX",
            "quote": "6.666666 USD"
        },
        "median_sbd2_price": {
            "base": "1.000000 SPHTX",
            "quote": "0.070733 EUR"
        },
        "median_sbd3_price": {
            "base": "1.000000 SPHTX",
            "quote": "0.079029 CHF"
        },
        "median_sbd4_price": {
            "base": "1.000000 SPHTX",
            "quote": "0.550184 CNY"
        },
        "median_sbd5_price": {
            "base": "1.000000 SPHTX",
            "quote": "0.062739 GBP"
        },
        "account_creation_fee": "0.050000 SPHTX"
    }
}

**Comment by ejossev** [comment]
Because cli_wallet is listening on that endpoint...

**Comment by MatusKysel** [comment]
> And how to enable The "alexandria_api"? thank's!

add this line `plugin = alexandria_api` in config.ini

**Comment by iguoke** [comment]
> > And how to enable The "alexandria_api"? thank's!
> 
> add this line `plugin = alexandria_api` in config.ini

After I Adding 

> > And how to enable The "alexandria_api"? thank's!
> 
> add this line `plugin = alexandria_api` in config.ini
But, After that,I running 
>./sophiatxd 
</var/lib/jenkins/workspace/SophiaTX_master-PUYTBECOVK66NM6FSV6YU5UHE5NIH7ACGS6LSH3G4IB2IWBWHP6Q/libraries/appbase/application.cpp(231): Throw in function appbase::abstract_plugin& appbase::application::get_plugin(const string&) const
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: unable to find plugin: alexandria_api

**Comment by iguoke** [comment]
> > And how to enable The "alexandria_api"? thank's!
> 
> add this line `plugin = alexandria_api` in config.ini

But, After that,I running
./sophiatxd
</var/lib/jenkins/workspace/SophiaTX_master-PUYTBECOVK66NM6FSV6YU5UHE5NIH7ACGS6LSH3G4IB2IWBWHP6Q/libraries/appbase/application.cpp(231): Throw in function appbase::abstract_plugin& appbase::application::get_plugin(const string&) const
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injectorstd::runtime_error >
std::exception::what: unable to find plugin: alexandria_api

**Comment by MatusKysel** [comment]
Because alexandria_api is available only in develop branch and you have latest release (master)

**Comment by iguoke** [comment]
> Because alexandria_api is available only in develop branch and you have latest release (master)

So，Which api is the most stable? I saw alexandria_C# and Alexandria_JS in your GitHub.

**Comment by ejossev** [comment]
Compile the latest develop or RC (rc_1_0_1) branch.
I would bet more on JS.

**Comment by iguoke** [comment]
> Compile the latest develop or RC (rc_1_0_1) branch.
> I would bet more on JS.
I met many ERRORS when Compiling develop!
And did you know that how to the others Exchanges (like kucoin,BitZ etc.)connect The nodes,
I work for HOTBIT Exchange and I need your guidance!
thank a lot!

**Comment by iguoke** [comment]
> Compile the latest develop or RC (rc_1_0_1) branch.
> I would bet more on JS.



> Compile the latest develop or RC (rc_1_0_1) branch.
> I would bet more on JS.
> I met many ERRORS when Compiling develop!
> And did you know that how to the others Exchanges (like kucoin,BitZ etc.)connect The nodes,
> I work for HOTBIT Exchange and I need your guidance!
> thank a lot!

Or，could give me a binary package for Centos7?

**Comment by iguoke** [comment]
> Try this one https://jenkins.sophiatx.com/job/SophiaTX/job/rc_1_0_1/16/artifact/sophiatx_%2316.tar.gz

It works, thinks!
