### ISSUE TITLE
App ID is not correctly serialized to binary, and is not part of the resulting signature for custom_json operation

### ISSUE THREAD

**Issue by IDVert3X** [SophiaTX/SophiaTX#160]
When serializing `custom_json` operation to binary ( which is later hashed to obtain a digest to sign ), `appId` is always serialized as `0`, ignoring the actual value.

Because of that, it's impossible to sign cusom_json operation for appId other than 0, as the resulting signature won't be accepted by the blockchain.
That's because the blockchain expects a signature for digest of binary where appId is 0, not the actual appId. Trying to use a signature of digest containing binary with appId other than 0 results in: `"missing required active authority:Missing Active Authority <account name>"`, which makes sense according to what I explained above.

This could also be a security vulnerability as the same signature is valid for 2^64-1 other transactions ( if you change just the appId in the operation JSON ).

### Steps to reproduce
Run this transaction JSON through `get_transaction_digest`, go to Alexandria log, look at the serialized binary - appId is always zero. [Example log can also be found here](https://github.com/SophiaTX/SophiaTX/files/2578348/appid-bug-alexandria-log.txt).
```json
{
	"ref_block_num": 185286,
	"ref_block_prefix": 1320089901,
	"expiration": "2018-11-13T21:08:52",
	"operations": [
		["custom_json", {
			"fee": "0.010000 SPHTX",
			"sender": "pato",
			"recipients": ["matus"],
			"appId": 2,
			"json": "{\"testKey\":\"integration test\"}"
		}]
	],
	"extensions": [],
	"signatures": []
}
```

### Example binaries
Example binaries ( as HEX ) generated for the JSON above can be found below.
The first one is generated using my library, the second is generated by Alexandria.
The actual appId is highlighted ( 16 characters / 8 bytes = uint64_t, encoded as little endian ).

*appId=0*
**My library:**
C6D32DF9AE4E643DEB5B010D10270000000000005350485458000000047061746F01056D61747573`0000000000000000`1E7B22746573744B6579223A22696E746567726174696F6E2074657374227D00
**Alexandria:**
C6D32DF9AE4E643DEB5B010D10270000000000005350485458000000047061746F01056D61747573`0000000000000000`1E7B22746573744B6579223A22696E746567726174696F6E2074657374227D00

*appId=1*
**My library:**
C6D32DF9AE4E643DEB5B010D10270000000000005350485458000000047061746F01056D61747573`0100000000000000`1E7B22746573744B6579223A22696E746567726174696F6E2074657374227D00
**Alexandria:**
C6D32DF9AE4E643DEB5B010D10270000000000005350485458000000047061746F01056D61747573`0000000000000000`1E7B22746573744B6579223A22696E746567726174696F6E2074657374227D00

*appId=2*
**My library:**
C6D32DF9AE4E643DEB5B010D10270000000000005350485458000000047061746F01056D61747573`0200000000000000`1E7B22746573744B6579223A22696E746567726174696F6E2074657374227D00
**Alexandria:**
C6D32DF9AE4E643DEB5B010D10270000000000005350485458000000047061746F01056D61747573`0000000000000000`1E7B22746573744B6579223A22696E746567726174696F6E2074657374227D00

**Comment by JakubFornadel** [comment]
ok i found where is the problem. you should use app_id, not appId

**Comment by IDVert3X** [comment]
I can confirm that this indeed is the case.

It's kinda weird that invalid json structure is silently "corrected", ignoring missing property ("app_id") and one additional property ("appId"), without throwing any exception.
I think there should be an explicit JSON structure validation as this is can get really confusing, this issue being an example.

**Comment by JakubFornadel** [comment]
ok, i am closing this issue as it is resolved. "explicit JSON structure validation" might be proposed and considered in the future planning...
