### ISSUE TITLE
Cannot connect to cli_wallet when ufw is enabled

### ISSUE THREAD

**Issue by nessgor** [SophiaTX/SophiaTX#87]
OS: Ubuntu 16.04 LTS

Everything is fine and I can even check the balance in my account using the cli_wallet **BEFORE** enabling the ufw to protect the server, after setup the ufw the node is still running normally which is good **BUT** when I connect to cli_wallet it shows:

```
sphtxadm@localhost:~/sphtxd$ ./cli_wallet -sws://127.0.0.1:9191
Logging RPC to file: logs/rpc/rpc.log
Starting a new wallet
933133ms main.cpp:157                  main                 ] wdata.ws_server: ws://127.0.0.1:9191
0 exception: unspecified
Timer Expired
    {"message":"Timer Expired"}
    websocket.cpp:444 operator()

    {"uri":"ws://127.0.0.1:9191"}
    websocket.cpp:673 connect

```

my ufw setting
```
root@localhost:~# ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), disabled (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
60000                      ALLOW IN    Anywhere

```

I have found a similar issue for websocket++ server behind ufw in [here](https://stackoverflow.com/questions/48557856/ufw-not-allowing-kurento-media-server-6-7-to-get-connected-through-ws-uri) and I follow the instruction to set the "net.ipv4.tcp_max_syn_backlog" to 1024 and enable the "tcp_syn_cookies" but the server still cannot be connected.

ufw should not get messed with the connection to localhost, because ufw got rules to allow packet via loopback. After I disable the ufw and flush the iptables then reboot the machine. everything goes fine again but I really don't want my node run naked.

At last, appreciate all efforts which had been made by SophiaTX team. Keep it up and SophiaTX will moon soon. :)

**Comment by nessgor** [comment]
More related issues

1. [steemit/steem: Websocket Timer Expired](https://github.com/steemit/steem/issues/35)
2. [zaphoyd/websocketpp: Cannot connect to websocketpp server when ufw firewall is installed](https://github.com/zaphoyd/websocketpp/issues/623)

**Comment by MatusKysel** [comment]
Hi, thank you for reporting this issue. I have updated websocketpp, so can you test [this](https://app.box.com/s/xjaey3jw8wwpss7g1oftey7kp6tivq41) version and leave us feedback if it is fixed for you.

**Comment by nessgor** [comment]
The server is now doing good using netfilter-persistent and iptables, will try ufw later

**Comment by nessgor** [comment]
Just tried and it works! Nice job

P.S. If anyone is going to use ufw, remember to open outgoing port 53 
```
sudo ufw allow out 53
```
as the DNS query may be blocked by ufw as stated here: [UFW is blocking DNS](https://unix.stackexchange.com/questions/131332/ufw-is-blocking-dns)
